### ISSUE TITLE
Survey results

### ISSUE THREAD

**Issue by dandevri** [iSirThijs/pt-tech#1]
Nice job on the survey! But can you give a summary of the results of the survey? Only thing I can look at is an `.csv` but that doesn't really tell me anything.

**Comment by dandevri** [comment]
And where did the survey took place? Who are the users of the survey?

**Comment by iamDistractech** [comment]
Thanks for this feedback. 👍 

I have updated the Wiki with a small summary of the results and added info about where the survey took place. see [1.0 Research](https://github.com/iSirThijs/pt-tech/wiki/1_research).
