### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [iSirThijs/pt-tech#2]
Your concept and user actions are very clear and well defined. I would indeed focus on adding the games to your profile and match based on those interests.

> When I create a profile, I want to add(and edit) the games I play, so matches know what games I like to play.

Then you can always enhance with:
> When I added games to my profile, I want to mark(and unmark) some as my absolute favorite, so matches know what my favorites are.
> When I want to add games to my profile, I want to import this from somewhere, so I don't have to manually add all my games.

Only thing you also need to focus on (I think) is how you are going to match the users. How does that work? Can you filter on games that people filled in? 

You also told me about unlocking different levels to see interests, that is another unique feature I would focus on but unlocking those levels through _chatting_ is too much for this project.

**Comment by iamDistractech** [comment]
>Only thing you also need to focus on (I think) is how you are going to match the users. How does that work? Can you filter on games that people filled in?

Users will be suggested a match based on their gaming library and their favorite games(and their preferences).  I've updated [2.0 Concept](https://github.com/iSirThijs/pt-tech/wiki/2_concept) to reflect this better. 

I'll probably come up with something a bit better, but for now I'll stick with this.

> You also told me about unlocking different levels to see interests, that is another unique feature I would focus on but unlocking those levels through chatting is too much for this project.

I'm not yet sure how I'm going to get this feature built in without chatting, but maybe I'll think of something later. For now I'll focus on adding games to the library and enhancing this.
