### ISSUE TITLE
Branding Research

### ISSUE THREAD

**Issue by dandevri** [iSirThijs/pt-tech#3]
Try to expand your branding research. Think about the css you are going to write. What components, colors & typography do you need?
* Create moodboards / styleguides etc.
* Create a css boilerplate

**Comment by iamDistractech** [comment]
Both the [research](https://github.com/iSirThijs/pt-tech/wiki/1.3_branding_research) and [style guide ](https://github.com/iSirThijs/pt-tech/wiki/2.1_styleguide)have been added to the wiki

The CSS boilerplate will be added soon to the code of this repository
